### ISSUE TITLE
Files are not deleted on AWS S3 after being deleted on Parse-Dashboard.

### ISSUE THREAD

**Issue by markmssd** [parse-server-modules/parse-server-s3-adapter#17]
I'm not sure if it's an issue, or if it's intended, but when on Parse-Dashboard, replacing/deleting a file does not delete it from AWS S3 bucket too. Not much of a problem, but in the long run, the bucket will be full of unused files...

If it's an issue, I can try to PR something.

**Comment by flovilmart** [comment]
Files were never deleted from parse.com and that feature is not available on parse-server either. A PR would be nice but seems rather complex and there is no tracking of created or deleted files

**Comment by markmssd** [comment]
Alright, I will close it for now in that case. If I can get something done I will PR it. Thanks!
