### ISSUE TITLE
The S3 file adapter seems not working

### ISSUE THREAD

**Issue by zhouhao27** [parse-server-modules/parse-server-s3-adapter#2]
I used S3 file adapter in my project with parse-server 2.2.4. Here is the code:

```
var S3Adapter = require('parse-server').S3Adapter

var api = new ParseServer({
  databaseURI:  config.dbUrl,
  cloud:        __dirname + '/cloud/main.js',
  appId:        config.appId,
  masterKey:    config.masterId, 
  clientKey:    'clientKey',
  serverURL:    config.serverUrl,
  fileAdapter: new S3Adapter(
    s3config.accessKey,
    s3config.secretKey,
    s3config.bucket,
    {directAccess: true,region:s3config.region}
  ),
```

But the file is not saved to my S3 bucket when I used REST API to upload a file like this:

```
curl -X POST \
  -H "X-Parse-Application-Id: myAppId" \
  -H "Content-Type: text/plain" \
  -d 'Hello, World!' \
  http://localhost:1337/parse/files/hello.txt
```

It returns:

> {"url":"http://localhost:1337/parse/files/myAppId/af5480f12aeaa449a3b424d4d8386670_hello.txt","name":"af5480f12aeaa449a3b424d4d8386670_hello.txt"}

Apparently it's not in S3 bucket. (I checked my S3 bucket, it's empty).

To make sure the S3 configuration is correct, I wrote a simple Nodejs app with the same S3. It works well. So the problem is either in parse-server or the S3 file adapter. Any idea? Thanks.

**Comment by flovilmart** [comment]
Does that check: https://github.com/parse-server-modules/parse-server-s3-adapter/blob/master/spec/test.spec.js#L38 seem to be your use case?

**Comment by flovilmart** [comment]
This is not a problem with S3, but with your configuration:

`fileAdapter:` should be `filesAdapter`

**Comment by zhouhao27** [comment]
WOW, silly mistake. Thanks
