### ISSUE TITLE
Upload image base64 > 1mb return 413 error => HEROKU - PARSE SERVER

### ISSUE THREAD

**Issue by Etto91** [parse-server-modules/parse-server-s3-adapter#29]
when i try to upload image i got this error: 
Error: request entity too large
    at readStream (/node_modules/raw-body/index.js:196:17)
    at getRawBody (/Users/ettorepanini/Sites/giovani-promesse-2.0/node_modules/raw-
my setup is: 

```
  region: 'eu-west-1',
  bucketPrefix: 'profile-img/',
  directAccess: false,
  signatureVersion: 'v4',
  globalCacheControl: 'public, max-age=86400'
```

this the bodyParser

```
app.use(bodyParser.json({limit: "50mb"))
app.use(bodyParser.urlencoded({extended: false}));
```

this error appear only for file > 1mb

```
 var imgData= url.replace(/^data:image\/(png|jpeg);base64,/, "");
var parseFile = new Parse.File(name, {base64:imgData});
console.log('Call save Parse file')
parseFile.save().then(function() {
  console.log(parseFile)
  Parse.Cloud.run('saveUserImage', {
  photo : parseFile,
  playerId : playerId,
}, {	
  success: function(result) {
											
```
in the parse server i have added this

`maxUploadSize: process.env.MAX_UPLOAD_SIZE || '20mb',`

I forgot something?
for file smaller then 1mb it works

**Comment by binzailani3136** [comment]
Is there any plan to fix this issue?
I am also going to use Heroku and AWS S3.
But if it only accepts the files less than 1Mb, it's a really problem.
Thanks

**Comment by flovilmart** [comment]
Can you post the full stack trace please?

**Comment by Etto91** [comment]
I solved this problem by uploading directly on s3 without creating parse file object. I can't post full stack trace

**Comment by flovilmart** [comment]
@Etto91 I'm confident this is just a configuration issue, also, if you're uploading directly to S3 you probably need a privileged access to S3 from the client which makes your bucket insecure (it not more of your AWS, depending on the configuration)

**Comment by Etto91** [comment]
also for me it could be a configuration issue, but I got this problem 2 months ago and now i'm uploading file by server side, and after that I save the cloudfront Link. Maybe @binzailani3136 can post the full stack trace.

**Comment by binzailani3136** [comment]
I've tested this through the parse and image files which are more than 1Mb and they were successfully uploaded to s3.
I've only read above issues and thought that this issue was not fixed yet.
I apologise to make you fraud.

My environments
-Parse server hosted on Heroku.
-Database is mLab MongoDB :: Mongodb(Free 500Mb)
-AWS S3
(I've added permission on my S3 bucket and also added PUT, POST permissions on CORS configuration of bucket)
![screen shot 2017-01-18 at 10 25 39 pm](https://cloud.githubusercontent.com/assets/20284956/22067689/466f1baa-ddcd-11e6-9e59-847aff673961.png)
![screen shot 2017-01-18 at 10 25 49 pm](https://cloud.githubusercontent.com/assets/20284956/22067690/470b7158-ddcd-11e6-9763-bcf6a87d2297.png)

I think, we can close this issue now.
Thanks

**Comment by flovilmart** [comment]
@binzailani3136 were you using the same file constructor as @Etto91 ? namely with `base64`?

**Comment by binzailani3136** [comment]
This is how I did.
`  
    Parse.initialize(settings.parseServerApplicationId, 'js-key', settings.parseServerMasterKey);
    Parse.serverURL = settings.parseServerURL;

    var s3Options = {
      "bucket": "xxx",
      "accessKey": "xxx",
      "secretKey": "xxx",
      "region": "eu-central-1",
      "bucketPrefix": "",
      "directAccess": false,
      "baseUrl": "https://s3.eu-central-1.amazonaws.com/",
      "signatureVersion": "v4",
      "globalCacheControl": "public, max-age=86400"
    };
    var s3Adapter = new S3Adapter(s3Options);

    const api = new ParseServer({
      appId: settings.parseServerApplicationId,
      masterKey: settings.parseServerMasterKey,
      serverURL: settings.parseServerURL,
      databaseURI: settings.parseServerDatabaseURI,
      filesAdapter: s3Adapter
    });`

**Comment by flovilmart** [comment]
no I mean when you upload your files, what was the code used?

**Comment by majidhassan** [comment]
Seems this issue was not solved yet. I get a 413 error when uploading files greater than 1mb.

**Comment by majidhassan** [comment]
My bad, it turned out it was the NGINX upload limit, which was defaulting to 1mb.

**Comment by flovilmart** [comment]
Closing as solved
