### ISSUE TITLE
Using parse-server-s3-adapter with Cognito?

### ISSUE THREAD

**Issue by psparago** [parse-server-modules/parse-server-s3-adapter#46]
Hi,

I'm not very well versed in S3 and I'm not a Parse server expert, so please forgive my ignorance.

I have an iOS app with a Parse backend in development. Currently, I'm saving and retrieving S3 files on the iOS client, mostly because I was unaware of the ability to use an adapter such as this. I'd like to migrate to this adapter if possible.

I was sort of stopped dead in my tracks by (as usual) Amazon S3 security. I use Cognito, which is recommended by Amazon and I don't (think I) pass keys and secrets. It seems that this adapter does not support Cognito access.

Can someone point me in the right direction please?

Thanks,
Peter...

**Comment by flovilmart** [comment]
Hi @psparago did you get a look at the [docs here](http://docs.parseplatform.org/parse-server/guide/#configuring-s3adapter)?

**Comment by psparago** [comment]
Hi @flovilmart, thank you very much for your speedy reply. I've been using Parse for a couple of years, but since Parse has gone open source, I wasn't aware of parseplatform.org.
