### ISSUE TITLE
S3 FileAdapter fails when bucket is located in Frankfurt

### ISSUE THREAD

**Issue by ststroppel** [parse-server-modules/parse-server-s3-adapter#5]
When setting up the s3 bucket with region Frankfurt (eu-central-1) the access from parse server / S3Adapter does not work. I'm using the latest version of the parse-server-s3-adapter 1.0.1. I'm testing it on my local parse installation (v 2.2.4). Without using the s3-adapter, the file is successfully saved. 
This issue has already been reported on https://github.com/ParsePlatform/parse-server/issues/1176 by another user.

This is how my configuration looks like:

```
var S3Adapter = require('parse-server-s3-adapter');

var api = new ParseServer({
  cloud: process.env.CLOUD_CODE_MAIN || __dirname + '/cloud/main.js',
  // ...
  filesAdapter: new S3Adapter(
      "---",
      "---",
      "bucket",
      {
          region: 'eu-central-1'
          //bucketPrefix: '',
          //directAccess: true
      }
  )
});
```

**Comment by flovilmart** [comment]
can you provide logs etc... Does your bucket exists already?

**Comment by ststroppel** [comment]
Bucket exists and has been created according to the wiki page for file adapters. Somehow, I don't get any meaningful logs. My /logs folder is empty and even with verbose on (npm start --verbose) I don't get anything which may be related to the file adapter.

**Comment by flovilmart** [comment]
to start in verbose that would bet `VERBOSE=1 npm start`

**Comment by ststroppel** [comment]
It seems that this is not working on windows, but with --verbose I get some additional log messages but nothing related to the s3 adapater.

**Comment by flovilmart** [comment]
ok I'll try to run some more tests when I have some time

**Comment by ststroppel** [comment]
I've modofied the adapter to get some console logs: this is the error message I got from the adapter:
```
{ [InvalidRequest: The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.]
  message: 'The authorization mechanism you have provided is not supported. Please use AWS4-HMAC-SHA256.',
  code: 'InvalidRequest',
  region: null,
  time: Thu Mar 31 2016 19:37:05 GMT+0200 (Mitteleuropäische Sommerzeit),
  requestId: 'xxx',
  extendedRequestId: 'xxx',
  statusCode: 400,
  retryable: false,
  retryDelay: 58.94708309788257 }

```

**Comment by flovilmart** [comment]
that's what I thought given the S3 documentation that EU requires v4 instead of v2 of the signature....

**Comment by ststroppel** [comment]
I already tested this. With this option, the adapter works :+1: 

I did the following change on line 56ff:
```
let s3Options = {
    accessKeyId: options.accessKey,
    secretAccessKey: options.secretKey,
    params: { Bucket: this._bucket },
    region: this._region,
    signatureVersion: 'v4'
};
```

**Comment by flovilmart** [comment]
you fell like making a PR?

**Comment by ststroppel** [comment]
will this also work for other locations? then I'll make a PR

**Comment by flovilmart** [comment]
there is also something else:

http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingBucket.html

With the bucket URL's

**Comment by ststroppel** [comment]
signature version 4 seems to be supported by every region. This looks sufficient to me. I'm not sure if we need such a map.

**Comment by flovilmart** [comment]
You're right, but we need the domain name to match the region

**Comment by OzgeAkin** [comment]
One another easy solution is making this signatureVersion field as an optional parameter that the user can give while creating the s3 adapter.  

And i wonder when this fix will be included?

**Comment by flovilmart** [comment]
@OzgeAkin the fix is not coded yet, feel free to submit a pull request.

**Comment by ststroppel** [comment]
@flovilmart I don't think we need an endpoint mapping. I just had a quick look on the aws-sdk source and found the following mapping rule: https://github.com/aws/aws-sdk-js/blob/master/lib/region_config.json
It looks like the endpoint is calculated automatically. I'm also using the version with signature version 4 in production and it's working perfectly for location Frankfurt. I would propose to either change the signature version to 4 in general or providing an optional parameter as suggested by @OzgeAkin

**Comment by flovilmart** [comment]
Let's make the default v4 and keep the parameter so one can downgrade to v2 if needed. What do you think?

**Comment by ststroppel** [comment]
I agree. I've submitted a PR with these changes

**Comment by acinader** [comment]
non us-east-1 users will also run into a problem here:

https://github.com/parse-server-modules/parse-server-s3-adapter/blob/master/index.js#L127

the url that is there will only work in us-east-1.

I'm in us-east-1 so i'm not going to try and fix, but it would require including the region in the url to access s3 directly (though accessing s3 directly is not a good idea as latency will be highly variable.  use cloud front instead and configure this adapter for direct access.)

**Comment by flovilmart** [comment]
This should be working now, closing.
