### ISSUE TITLE
PARSE_SERVER_FILES_ADAPTER no longer works.

### ISSUE THREAD

**Issue by 5amfung** [parse-server-modules/parse-server-s3-adapter#7]
Is PARSE_SERVER_FILES_ADAPTER in the [instructions](https://github.com/ParsePlatform/parse-server/wiki/Configuring-File-Adapters#using-environment-variables) still correct and applicable?

Somehow my file is still written to mongo instead to S3.

**Comment by si294r** [comment]
Same here... My parse-server run with PM2 on ubuntu 14.04 ... and it's not work with this config 
```
    "env": {
      ....
      "PARSE_SERVER_FILES_ADAPTER": "parse-server-s3-adapter",
      "S3_ACCESS_KEY": "#########",
      "S3_SECRET_KEY": "#########",
      "S3_BUCKET": "my-bucket-parse-development",
      ....
    }
``` 
the file is not saved to my S3 bucket, but its work after i make change in file /usr/lib/node_modules/parse-server/lib/cli/parse-server.js 
```
...
if (!options.appId || !options.masterKey || !options.serverURL) {
  ...
}

// create S3Adapter object if FILES_ADAPTER is S3
if ('parse-server-s3-adapter' == process.env.PARSE_SERVER_FILES_ADAPTER) {
  options.filesAdapter = new _index.S3Adapter({
        accessKey: process.env.S3_ACCESS_KEY || '',
        secretKey: process.env.S3_SECRET_KEY || '',
        bucket: process.env.S3_BUCKET || '',
        region: process.env.S3_REGION || ''
  });
}

var app = (0, _express2.default)();
var api = new _index.ParseServer(options);
...
```

**Comment by bigdoghung** [comment]
Should the S3_BASE_URL look something like this: "https://s3-us-west-1.amazonaws.com/bucketname" "?

**Comment by Abderezai** [comment]
I'm having same issue... Please advise.

**Comment by acinader** [comment]
@bigdoghung looks right; however, you can be sure by going to the aws console, selecting a file and clicking properties.  it'll show you the url and you can click on it to make sure that all credentials, etc. are working.

**Comment by TonyTangAndroid** [comment]
I also run into this issue. I could not make it correctly using ecosystem.json configuration.

**Comment by flovilmart** [comment]
Closing as too old, please reopen a new issue if needed.
